[workspace]
members = ["workspace/apps/perpetuals/contracts", "workspace/packages/contracts"]


[workspace.dependencies]
starknet = "2.9.2"
assert_macros = "2.9.2"
openzeppelin = "0.20.0"
openzeppelin_testing = "0.20.0"
snforge_std = "0.34.0"

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
