[workspace]
members = ["workspace/apps/perpetuals/contracts", "workspace/packages/contracts"]


[workspace.dependencies]
starknet = "2.8.5"
assert_macros = "2.8.5"
openzeppelin = "0.19.0"
snforge_std = "0.33.0"

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
