[workspace]
members = ["workspace/apps/perpetuals/contracts", "workspace/packages/contracts"]


[workspace.dependencies]
starknet = "2.10.1"
assert_macros = "2.10.1"
openzeppelin = "1.0.0"
openzeppelin_testing = "1.0.0"
snforge_std = "0.34.0"
contracts_commons = { path = "workspace/packages/contracts" }

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"
