[package]
name = "perpetuals"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet.workspace = true
contracts_commons = { path = "../../../packages/contracts" }
openzeppelin.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.fmt]
sort-module-level-items = true
