[package]
name = "perpetuals"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
contracts_commons.workspace = true
openzeppelin.workspace = true

[dev-dependencies]
assert_macros.workspace = true
snforge_std.workspace = true
openzeppelin_testing.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "SNFORGE_BACKTRACE=1 snforge test"

[tool.fmt]
sort-module-level-items = true

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[[test]]
name = "perpetuals_unittest"
build-external-contracts = [
    "contracts_commons::erc20_mocks::DualCaseERC20Mock",
    "openzeppelin_presets::account::AccountUpgradeable"
]
